---
ID: "9985b2fc-4193-4d54-87cc-01535fb3d23e"
Parent: "69fcec09-412f-4780-ac36-690a08acb1ba"
Template: "69fcec09-412f-4780-ac36-690a08acb1ba"
Path: /sitecore/templates/Project/HubSpot/New template/__Standard Values
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{94E10EB1-9A05-4D62-BA76-720E625F75A5}">
        <r
          id="{44F1E2FC-D67E-4187-B34F-113CED3B69BF}"
          ph="Home"
          uid="{CBF2CD22-5434-49CB-9DF8-496C8C49B81B}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220824T062132Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "11427ae1-0a80-41d4-907e-9524ff9401a1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220824T075726Z
